### PR TITLE
MBStyle - Additions to MBStyleSpriteGenerator

### PR DESCRIPTION
**Pull request by mattkrusz**
- Now includes ShapeMarkFactory shapes (prefix must be added in sprite index file)
- Now draws the shapes with default black / gray styling
- Saves them all to mark-sprite-output resources folder
- Changed default scale to 32
- Ensured all shapes have GeoTools default orientation (star, triangle, slash, backslash were 180* rotated)

### CODE REVIEW

**Comment by tbarsballe** [comment]
Question - weren't we planning on outputting these as PNG so that we could use them in spritesheets?

**Comment by mattkrusz** [comment]
spritezero actually takes the individual icons as SVG, and combines them into a png spritesheet while providing the capability to resize them for high DPI devices.

**Comment by tbarsballe** [comment]
Well, thats quite convenient then. Given that, changes look good.

I'm going to go ahead and merge this into my branch, since this is an improvement upon what is currently there. I can't imagine this ever making it onto master (except maybe as part of the docs / dev guide ?), but it will be useful to have a branch with this functionality.

**Comment by mattkrusz** [comment]
Sounds good to me.

**Pull request merged**
